BoosterBundle\Entity\Faq:
    type: entity
    table: null
    repositoryClass: BoosterBundle\Repository\FaqRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        question:
            type: string
            length: 255
            unique: false
        answer:
            type: text
            unique: false
        category:
            type: string
            length: 255
            unique: false

    lifecycleCallbacks: {  }
