BoosterBundle\Entity\ProjectSubsciption:
    type: entity
    table: project_subsciption
    indexes:
        fk_project_subsciption_booster1_idx:
            columns:
                - booster_id
        fk_project_subsciption_project1_idx:
            columns:
                - project_id
    uniqueConstraints:
        id_UNIQUE:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        message:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    oneToOne:
        booster:
            targetEntity: Booster
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                booster_id:
                    referencedColumnName: id
            orphanRemoval: false
        project:
            targetEntity: Project
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
