<?php

namespace BoosterBundle\Repository;

/**
 * FixturesTestUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FixturesTestUserRepository extends \Doctrine\ORM\EntityRepository
{
}
