<?php

namespace BoosterBundle\Repository;

/**
 * messengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessengerRepository extends \Doctrine\ORM\EntityRepository
{
    function myMessages($username){
        $req = $this->createQueryBuilder('a')
            ->where('a.user1 = :username')
            ->orWhere('a.user2 = :username')
            ->setParameter('username', $username)
            ->getQuery();

        return $req->getResult();
    }
}
