<?php

namespace BoosterBundle\Repository;

/**
 * messengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessengerRepository extends \Doctrine\ORM\EntityRepository
{
    public function myMessages($userId){
        $req = $this->createQueryBuilder('a')
            ->where('a.user1 = :userId')
            ->orWhere('a.user2 = :userId')
            ->orderBy('a.title')
            ->setParameter('userId', $userId)
            ->getQuery();

        return $req->getResult();
    }
    public function cancelMessages($title, $newTitle){
        $qb = $this->createQueryBuilder('a')
            ->update()
            ->set('a.title', '?1')
            ->where('a.title = ?2')
            ->setParameter(1, $newTitle)
            ->setParameter(2, $title)
            ->getQuery();

        return $qb->execute();
    }
}
