<?php

namespace BoosterBundle\Repository;

/**
 * messengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessengerRepository extends \Doctrine\ORM\EntityRepository
{
    function myMessages($username){
        $req = $this->createQueryBuilder('a')
            ->where('a.user1 = :username')
            ->orWhere('a.user2 = :username')
            ->orderBy('a.title')
            ->setParameter('username', $username)
            ->getQuery();

        return $req->getResult();
    }

    function insertReadOne($username, $title){
        $qb = $this->createQueryBuilder('a');
        $req = $qb->update()
            ->set('a.user1Read', $qb->expr()->literal(1))
            ->where('a.title = :title')
            ->andWhere('a.user1 = :username')
            ->setParameter('title', $title)
            ->setParameter('username', $username)
            ->getQuery();

        return $req->execute();
    }

    function insertReadTwo($username, $title){
        $qb = $this->createQueryBuilder('a');
        $req = $qb->update()
            ->set('a.user2Read', $qb->expr()->literal(1))
            ->where('a.title = :title')
            ->andWhere('a.user2 = :username')
            ->setParameter('title', $title)
            ->setParameter('username', $username)
            ->getQuery();

        return $req->execute();
    }
}
