<?php

namespace BoosterBundle\Repository;
use BoosterBundle\Controller\RegistrationController;

/**
 * FixturesTestUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegistrationRepository extends \Doctrine\ORM\EntityRepository
{

}