#project_index:
#    path:     /
#    defaults: { _controller: "BoosterBundle:Project:index" }
#    methods:  GET

#project_show:
#    path:     /{id}/show
#    defaults: { _controller: "BoosterBundle:Project:show" }
#    methods:  GET

#project_new:
#    path:     /new
#    defaults: { _controller: "BoosterBundle:Project:new" }
#    methods:  [GET, POST]

#project_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "BoosterBundle:Project:edit" }
#    methods:  [GET, POST]

#project_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "BoosterBundle:Project:delete" }
#    methods:  DELETE
